import type { DemoData } from "./types";

export const seedData: DemoData = {
  members: [
    {
      id: "member-maya",
      name: "Maya Chen",
      role: "Founder",
      company: "Northstar Labs",
      location: "Austin",
      expertise: ["B2B SaaS", "operator network", "product strategy"],
      trustSignals: ["Founding member circle", "3 accepted referrals", "direct operator overlap"],
      availability: "Open",
      relationshipStrength: 88,
    },
    {
      id: "member-lena",
      name: "Lena Ortiz",
      role: "Fractional CFO",
      company: "Atlas Finance Partners",
      location: "Dallas",
      expertise: ["fractional finance", "Series A readiness", "SaaS metrics", "board reporting"],
      trustSignals: ["prior accepted referral", "direct operator overlap", "worked with two members"],
      availability: "Selective",
      relationshipStrength: 94,
    },
    {
      id: "member-darius",
      name: "Darius Patel",
      role: "Managing Partner",
      company: "Kinetic Growth",
      location: "Chicago",
      expertise: ["go-to-market", "RevOps", "pricing", "CRM systems"],
      trustSignals: ["closed 2 network deals", "agency partner overlap"],
      availability: "Open",
      relationshipStrength: 81,
    },
    {
      id: "member-evelyn",
      name: "Evelyn Brooks",
      role: "Principal",
      company: "Summit Talent",
      location: "Nashville",
      expertise: ["executive search", "finance leaders", "private equity operators"],
      trustSignals: ["vetted service provider", "member sponsor verified"],
      availability: "Limited",
      relationshipStrength: 76,
    },
    {
      id: "member-noah",
      name: "Noah Kim",
      role: "Partner",
      company: "Harbor Legal",
      location: "Denver",
      expertise: ["M&A counsel", "SaaS contracts", "data privacy"],
      trustSignals: ["trusted by founding circle", "rapid response history"],
      availability: "Selective",
      relationshipStrength: 73,
    },
  ],
  opportunities: [
    {
      id: "opp-fractional-cfo",
      requesterId: "member-maya",
      title: "Fractional CFO for a Series A SaaS company",
      description:
        "Northstar Labs needs a finance operator who can clean up SaaS metrics, build a board package, and prepare for a Series A process.",
      category: "Finance",
      urgency: "This week",
      keywords: ["fractional finance", "Series A", "SaaS metrics", "board reporting"],
    },
    {
      id: "opp-revops",
      requesterId: "member-maya",
      title: "RevOps audit before enterprise pipeline push",
      description:
        "A member company needs help rationalizing HubSpot stages, attribution, and pricing packages before hiring sales leadership.",
      category: "Growth",
      urgency: "This month",
      keywords: ["RevOps", "pricing", "CRM systems", "go-to-market"],
    },
  ],
  referrals: [
    {
      id: "ref-001",
      opportunityId: "opp-fractional-cfo",
      fromMemberId: "member-maya",
      toMemberId: "member-lena",
      status: "accepted",
      note: "Lena previously helped a network member build a board-ready finance model.",
    },
    {
      id: "ref-002",
      opportunityId: "opp-revops",
      fromMemberId: "member-maya",
      toMemberId: "member-darius",
      status: "sent",
      note: "Darius is reviewing the GTM systems brief.",
    },
  ],
  activity: [
    {
      id: "act-001",
      label: "Drafted",
      detail: "AI prepared a double opt-in note for Lena Ortiz.",
      timestamp: "9:12 AM",
    },
    {
      id: "act-002",
      label: "Sent",
      detail: "Maya sent the intro request with context and urgency.",
      timestamp: "9:18 AM",
    },
    {
      id: "act-003",
      label: "Accepted",
      detail: "Lena accepted and asked for the company brief.",
      timestamp: "10:04 AM",
    },
    {
      id: "act-004",
      label: "Closed",
      detail: "Awaiting outcome after first finance working session.",
      timestamp: "Pending",
    },
  ],
};
