import type { DemoData } from "./types";

export const seedData: DemoData = {
  members: [
    {
      id: "member-maya",
      name: "Maya Chen",
      role: "Founder",
      company: "Northstar Labs",
      location: "Austin",
      expertise: ["B2B SaaS", "operator network", "product strategy"],
      trustSignals: ["Founding member circle", "3 accepted referrals", "direct operator overlap"],
      availability: "Open",
      relationshipStrength: 88,
    },
    {
      id: "member-lena",
      name: "Lena Ortiz",
      role: "Fractional CFO",
      company: "Atlas Finance Partners",
      location: "Dallas",
      expertise: ["fractional finance", "Series A readiness", "SaaS metrics", "board reporting"],
      trustSignals: ["prior accepted referral", "direct operator overlap", "worked with two members"],
      availability: "Selective",
      relationshipStrength: 94,
    },
    {
      id: "member-darius",
      name: "Darius Patel",
      role: "Managing Partner",
      company: "Kinetic Growth",
      location: "Chicago",
      expertise: ["go-to-market", "RevOps", "pricing", "CRM systems"],
      trustSignals: ["closed 2 network deals", "agency partner overlap"],
      availability: "Open",
      relationshipStrength: 81,
    },
    {
      id: "member-evelyn",
      name: "Evelyn Brooks",
      role: "Principal",
      company: "Summit Talent",
      location: "Nashville",
      expertise: ["executive search", "finance leaders", "private equity operators"],
      trustSignals: ["vetted service provider", "member sponsor verified"],
      availability: "Limited",
      relationshipStrength: 76,
    },
    {
      id: "member-noah",
      name: "Noah Kim",
      role: "Partner",
      company: "Harbor Legal",
      location: "Denver",
      expertise: ["M&A counsel", "SaaS contracts", "data privacy"],
      trustSignals: ["trusted by founding circle", "rapid response history"],
      availability: "Selective",
      relationshipStrength: 73,
    },
    {
      id: "member-sophia",
      name: "Sophia Ramirez",
      role: "COO",
      company: "Meridian Health Ventures",
      location: "Phoenix",
      expertise: ["clinic expansion", "payer strategy", "healthcare operations", "provider networks"],
      trustSignals: ["opened 4 regional markets", "member-backed operator"],
      availability: "Open",
      relationshipStrength: 86,
    },
    {
      id: "member-jonathan",
      name: "Jonathan Reed",
      role: "CEO",
      company: "Forge Industrial",
      location: "Pittsburgh",
      expertise: ["industrial automation", "manufacturing", "channel partnerships", "field service"],
      trustSignals: ["closed channel referral", "operator peer verified"],
      availability: "Selective",
      relationshipStrength: 79,
    },
    {
      id: "member-amara",
      name: "Amara Singh",
      role: "Partner",
      company: "Northline Capital",
      location: "New York",
      expertise: ["private equity", "acquisition search", "debt financing", "operator diligence"],
      trustSignals: ["co-invested with two members", "warm lender network"],
      availability: "Limited",
      relationshipStrength: 84,
    },
    {
      id: "member-caleb",
      name: "Caleb Wright",
      role: "CTO",
      company: "SignalWorks",
      location: "Seattle",
      expertise: ["AI infrastructure", "security reviews", "data platforms", "vendor diligence"],
      trustSignals: ["technical diligence lead", "rapid response history"],
      availability: "Open",
      relationshipStrength: 82,
    },
    {
      id: "member-priya",
      name: "Priya Shah",
      role: "Founder",
      company: "Ledgerly",
      location: "San Francisco",
      expertise: ["embedded payments", "fintech compliance", "bank partnerships", "risk operations"],
      trustSignals: ["regulated-market founder", "referred by finance circle"],
      availability: "Selective",
      relationshipStrength: 78,
    },
    {
      id: "member-marcus",
      name: "Marcus Ellis",
      role: "Principal",
      company: "CivicGrid",
      location: "Atlanta",
      expertise: ["municipal procurement", "govtech", "grant programs", "public-sector sales"],
      trustSignals: ["city CIO network", "two accepted civic introductions"],
      availability: "Open",
      relationshipStrength: 80,
    },
    {
      id: "member-talia",
      name: "Talia Morrison",
      role: "Head of People",
      company: "Orbit Labs",
      location: "Boston",
      expertise: ["executive coaching", "compensation design", "remote teams", "leadership onboarding"],
      trustSignals: ["trusted talent advisor", "founder coach verified"],
      availability: "Selective",
      relationshipStrength: 71,
    },
    {
      id: "member-henry",
      name: "Henry Locke",
      role: "Advisor",
      company: "Craft Retail Group",
      location: "Minneapolis",
      expertise: ["ecommerce", "inventory planning", "marketplaces", "retail operations"],
      trustSignals: ["operator turnaround history", "marketplace partner network"],
      availability: "Open",
      relationshipStrength: 69,
    },
    {
      id: "member-isabel",
      name: "Isabel Grant",
      role: "Managing Director",
      company: "Blue Oak Philanthropy",
      location: "Charlotte",
      expertise: ["nonprofit strategy", "donor networks", "family offices", "board governance"],
      trustSignals: ["family office connector", "board placement history"],
      availability: "Limited",
      relationshipStrength: 74,
    },
  ],
  opportunities: [
    {
      id: "opp-fractional-cfo",
      requesterId: "member-maya",
      title: "Fractional CFO for a Series A SaaS company",
      description:
        "Northstar Labs needs a finance operator who can clean up SaaS metrics, build a board package, and prepare for a Series A process.",
      category: "Finance",
      urgency: "This week",
      keywords: ["fractional finance", "Series A", "SaaS metrics", "board reporting"],
    },
    {
      id: "opp-revops",
      requesterId: "member-maya",
      title: "RevOps audit before enterprise pipeline push",
      description:
        "A member company needs help rationalizing HubSpot stages, attribution, and pricing packages before hiring sales leadership.",
      category: "Growth",
      urgency: "This month",
      keywords: ["RevOps", "pricing", "CRM systems", "go-to-market"],
    },
    {
      id: "opp-clinic-expansion",
      requesterId: "member-sophia",
      title: "Regional clinic expansion operator",
      description:
        "A healthcare group is evaluating two new markets and needs a trusted operator who understands payer strategy and provider networks.",
      category: "Healthcare",
      urgency: "This month",
      keywords: ["clinic expansion", "payer strategy", "provider networks", "healthcare operations"],
    },
    {
      id: "opp-ai-security-review",
      requesterId: "member-noah",
      title: "AI vendor security review",
      description:
        "A legal client needs a technical reviewer for AI infrastructure, data handling, and vendor diligence before procurement approval.",
      category: "Technology",
      urgency: "This week",
      keywords: ["AI infrastructure", "security reviews", "data platforms", "vendor diligence"],
    },
    {
      id: "opp-acquisition-search",
      requesterId: "member-jonathan",
      title: "Acquisition target screen for industrial services",
      description:
        "Forge Industrial is screening industrial services targets and wants a capital partner familiar with operator diligence and debt financing.",
      category: "Capital",
      urgency: "Exploratory",
      keywords: ["acquisition search", "debt financing", "operator diligence", "private equity"],
    },
    {
      id: "opp-payments-partner",
      requesterId: "member-henry",
      title: "Embedded payments partner for marketplace launch",
      description:
        "A retail marketplace needs advice on embedded payments, risk operations, and bank partnership options before launch.",
      category: "Fintech",
      urgency: "This month",
      keywords: ["embedded payments", "bank partnerships", "risk operations", "fintech compliance"],
    },
    {
      id: "opp-vp-sales-search",
      requesterId: "member-darius",
      title: "VP Sales search for vertical SaaS",
      description:
        "A bootstrapped vertical SaaS company needs an executive search partner who can calibrate sales leadership and compensation.",
      category: "Talent",
      urgency: "This week",
      keywords: ["executive search", "compensation design", "leadership onboarding", "finance leaders"],
    },
    {
      id: "opp-municipal-procurement",
      requesterId: "member-marcus",
      title: "Municipal procurement path for infrastructure software",
      description:
        "A govtech founder needs introductions to city operators who understand procurement, grants, and public-sector sales cycles.",
      category: "Public sector",
      urgency: "This month",
      keywords: ["municipal procurement", "grant programs", "public-sector sales", "govtech"],
    },
  ],
  referrals: [
    {
      id: "ref-001",
      opportunityId: "opp-fractional-cfo",
      fromMemberId: "member-maya",
      toMemberId: "member-lena",
      status: "accepted",
      note: "Lena previously helped a network member build a board-ready finance model.",
    },
    {
      id: "ref-002",
      opportunityId: "opp-revops",
      fromMemberId: "member-maya",
      toMemberId: "member-darius",
      status: "sent",
      note: "Darius is reviewing the GTM systems brief.",
    },
    {
      id: "ref-003",
      opportunityId: "opp-clinic-expansion",
      fromMemberId: "member-sophia",
      toMemberId: "member-marcus",
      status: "drafted",
      note: "Marcus may know two city health leaders evaluating outpatient access grants.",
    },
    {
      id: "ref-004",
      opportunityId: "opp-ai-security-review",
      fromMemberId: "member-noah",
      toMemberId: "member-caleb",
      status: "accepted",
      note: "Caleb accepted a technical diligence call this week.",
    },
    {
      id: "ref-005",
      opportunityId: "opp-acquisition-search",
      fromMemberId: "member-jonathan",
      toMemberId: "member-amara",
      status: "sent",
      note: "Amara asked for target criteria and EBITDA range.",
    },
    {
      id: "ref-006",
      opportunityId: "opp-payments-partner",
      fromMemberId: "member-henry",
      toMemberId: "member-priya",
      status: "accepted",
      note: "Priya offered to review payment risk assumptions before partner outreach.",
    },
    {
      id: "ref-007",
      opportunityId: "opp-vp-sales-search",
      fromMemberId: "member-darius",
      toMemberId: "member-evelyn",
      status: "drafted",
      note: "Evelyn is a strong match if timing works despite limited availability.",
    },
    {
      id: "ref-008",
      opportunityId: "opp-vp-sales-search",
      fromMemberId: "member-darius",
      toMemberId: "member-talia",
      status: "sent",
      note: "Talia can help calibrate compensation and onboarding requirements.",
    },
    {
      id: "ref-009",
      opportunityId: "opp-municipal-procurement",
      fromMemberId: "member-marcus",
      toMemberId: "member-sophia",
      status: "accepted",
      note: "Sophia has provider-network context relevant to municipal health programs.",
    },
    {
      id: "ref-010",
      opportunityId: "opp-payments-partner",
      fromMemberId: "member-henry",
      toMemberId: "member-noah",
      status: "closed",
      note: "Noah shared data privacy constraints for payment partner diligence.",
    },
    {
      id: "ref-011",
      opportunityId: "opp-acquisition-search",
      fromMemberId: "member-jonathan",
      toMemberId: "member-lena",
      status: "declined",
      note: "Lena declined because the target screen is too early for finance-model work.",
    },
    {
      id: "ref-012",
      opportunityId: "opp-clinic-expansion",
      fromMemberId: "member-sophia",
      toMemberId: "member-isabel",
      status: "sent",
      note: "Isabel may know family office funders interested in regional care access.",
    },
    {
      id: "ref-013",
      opportunityId: "opp-ai-security-review",
      fromMemberId: "member-noah",
      toMemberId: "member-priya",
      status: "drafted",
      note: "Priya can pressure-test regulated-data risk from the fintech side.",
    },
  ],
  activity: [
    {
      id: "act-001",
      label: "Drafted",
      detail: "AI prepared a double opt-in note for Lena Ortiz.",
      timestamp: "9:12 AM",
    },
    {
      id: "act-002",
      label: "Sent",
      detail: "Maya sent the intro request with context and urgency.",
      timestamp: "9:18 AM",
    },
    {
      id: "act-003",
      label: "Accepted",
      detail: "Lena accepted and asked for the company brief.",
      timestamp: "10:04 AM",
    },
    {
      id: "act-004",
      label: "Closed",
      detail: "Awaiting outcome after first finance working session.",
      timestamp: "Pending",
    },
    {
      id: "act-005",
      label: "Screened",
      detail: "Conduit screened 14 members against 8 open asks.",
      timestamp: "Yesterday",
    },
    {
      id: "act-006",
      label: "Accepted",
      detail: "Caleb accepted the AI vendor diligence intro.",
      timestamp: "Yesterday",
    },
    {
      id: "act-007",
      label: "Sent",
      detail: "Amara received the industrial acquisition brief.",
      timestamp: "Mon",
    },
    {
      id: "act-008",
      label: "Drafted",
      detail: "Evelyn and Talia were shortlisted for the VP Sales search.",
      timestamp: "Mon",
    },
    {
      id: "act-009",
      label: "Accepted",
      detail: "Priya agreed to review payment partner risk assumptions.",
      timestamp: "Fri",
    },
    {
      id: "act-010",
      label: "Declined",
      detail: "Lena declined the acquisition screen because the ask was too early.",
      timestamp: "Thu",
    },
    {
      id: "act-011",
      label: "Sent",
      detail: "Isabel received the clinic expansion funding context.",
      timestamp: "Wed",
    },
    {
      id: "act-012",
      label: "Closed",
      detail: "Noah completed the privacy diligence note for the payments launch.",
      timestamp: "Tue",
    },
  ],
};
